name: build multi-arch images

on:
  push:
    branches: [ mult_arch_build ]
  pull_request: 
    branches: [ master ]
  schedule: 
  - cron:  '5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - 
        name: Log in to Red Hat Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
        
      -
        name: Buildah push
        if: github.event_name == 'scedule' || github.event_name == 'push'
        uses: redhat-actions/buildah-build@v2.5.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            alvarogg777/mlflow:latest
            alvarogg777/mlflow:1.18.0
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
