name: build multi-arch images

on:
  push:
    branches: [ mult_arch_build ]
  pull_request: 
    branches: [ master ]
  schedule: 
  - cron:  '5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - 
        name: Log in to Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
        
      -
        name: Buildah push
        id: build-image
        if: github.event_name == 'scedule' || github.event_name == 'push'
        uses: redhat-actions/buildah-build@v2.5.1
        with:
          context: .
          dockerfiles: ./Dockerfile
          archs: linux/amd64,linux/arm64
          push: true
          tags: |
            alvarogg777/mlflow:latest
            alvarogg777/mlflow:1.18.0
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
      
      - 
        name: Push To Registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: mlflow
          tags: ${{ steps.build-image.outputs.tags }}
#           tags: ${{ steps.build-image.outputs.tags }}
          registry: docker.io/alvarog777
          username: ${{ secrets.REGISTRY_PASSWORD }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - 
        name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
